### ISSUE TITLE
Exceptions thrown from ExecutorService threads are silently ignored

### ISSUE THREAD

**Issue by kubamracek** [ever-been/everBeen#104]
The `run` method of ResultsDispatcher and possibly other (!) Runnables should be wrapped in a catch-all block, because these Runnables are invoked from ExecutorService. Exceptions in these methods are silently ignored and thread silently exits.

**Comment by donarus** [comment]
`EphemerousConsumer` still doesn't implement pokemon blocks, as some other classes that implement threading through `ExecutorService`. See `LingeringConsumer` for model pokemon block implementation.

**Comment by radek-macha** [comment]
The only remaining use of `ExecutorService` is in `LocalKeyScanner`. Given that @sixtam will probably be doing a lot of coding in this area, I'm reassigning the issue to him to ensure potential new code gets pokemon treatment as well.
