### ISSUE TITLE
task descriptor and context task descriptor templates (in BPK,WI and SR)

### ISSUE THREAD

**Issue by donarus** [ever-been/everBeen#105]
It should be possible to add TD and CTD templates to bpk (bpk plugin should handle it).

It should be possible to store, list and delete TD and CTD templates from uploaded BPKs in SW repository, delete TD and CTD templates for deleted BPKs and add user-defined templates to concrete BPKs.

In WI it should be possible to select prefilled TD/CTD template, add new template, delete template and edit template.

**Comment by kubamracek** [comment]
We will not implement deleting and modifying descriptors. Other stuff is done.
