### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by sixtam** [ever-been/everBeen#110]
Decide what license EverBEEN should be released under.

We wrote most of the code so we have the liberty (i think) to release under different license than GNU LGPL v2.1.

Some code was written as part of WillBEEN by @andrejpodzimek (JAXB related code).

**Comment by donarus** [comment]
One small note: We should check license of all 3rd party libraries used by "BEEN" before thinking about licence change.

**Comment by radek-macha** [comment]
Fixed yesterday by adding LGPL to the LICENSE file in project root
