### ISSUE TITLE
-SNAPSHOT version causes exception in ZipFileUtil.unzipToDir

### ISSUE THREAD

**Issue by sixtam** [ever-been/everBeen#112]
We changed version from 3.0.0 to 3.0.0-SNAPSHOT in task-test/pom.xml (and also in td.xml) and were rewarded by an zip related exception. WTF? Only few files were extracted ...

I would use an java zip library but they all suck as far as i know ... does anybody know a good java zip library?

**Comment by radek-macha** [comment]
I'll look into this, the ZipStream work handling unpacking BPKs is something I devised a couple of months ago.

**Comment by radek-macha** [comment]
I tried modifying the code using [ZipArchiveInputStream](http://commons.apache.org/proper/commons-compress/apidocs/org/apache/commons/compress/archivers/zip/ZipArchiveInputStream.html), which reports a similar error. It could be that something is off with the BPK packaging.

**Comment by radek-macha** [comment]
The issue was caused by a concurrent read and write of the same file (enabled by SNAPSHOT). The reason was that SoftwareRepository was using the same folder as BPK storage as the HostRuntime was using for caching these.
