### ISSUE TITLE
Configuration persistence

### ISSUE THREAD

**Issue by radek-macha** [ever-been/everBeen#117]
Persistence for TD, TCD

**Comment by radek-macha** [comment]
@donarus Any ideas how to test it?

**Comment by donarus** [comment]
I will test it as soon as possible. Probably today, when I get done with implementation of deleting folders on hostruntime.

**Comment by radek-macha** [comment]
- descriptors should be saved automagically every time a context is launched
- named descriptors need a slight addition to the webflow (named descriptor retrieval)

**Comment by kubamracek** [comment]
Fixed by c04623c4409bffd9a901c64da155cf809438dc71
