### ISSUE TITLE
Result eviction on Task or TaskContext fail

### ISSUE THREAD

**Issue by radek-macha** [ever-been/everBeen#119]
Persistent objects must be purged

**Comment by donarus** [comment]
Create `PersistentContextState`. See `PersistentTaskState`. Save it to persistence once a context finishes.

**Comment by radek-macha** [comment]
Will follow up on naming conventions in #179

**Comment by radek-macha** [comment]
@sixtam If you have any spare time on your hands, I'd be grateful if you could zip-read through the source code to see if there's no contradiction with what we discussed earlier.
