### ISSUE TITLE
Benchmark API tune-up

### ISSUE THREAD

**Issue by radek-macha** [ever-been/everBeen#121]
Review existing API for benchmark control, consider completeness and ease of use. Tweak it up if need be.

**Comment by sixtam** [comment]
I would appreciate onContextFailed([TaskContextDescriptor descriptor | String contextId]) method which would be invoked if a context fails, to give a benchmark chance to do something ... clean up / resubmit.

Also init()/destroy() function for bechmark/generator task would be nice (!resubmitting!)
