### ISSUE TITLE
Task/TaskContext/Benchmark detail pages

### ISSUE THREAD

**Issue by radek-macha** [ever-been/everBeen#129]
On task detail, if the task is FAILED, allow leftover data deletion. Also ensure that the working folder of a task is not deleted if the task status reaches FAILED.

**Comment by donarus** [comment]
Instead of leftover data deletion of failed tasks implement deletion of all leftover data when the task/context/benchmark is removed from cluster, no matter if it is in state FINISHED or FAILED.
