### ISSUE TITLE
WI - trying to kill benchmark with running contexts results in exception

### ISSUE THREAD

**Issue by sixtam** [ever-been/everBeen#143]
When trying to remove (i.e. aborted) benchmark with running context the web interface gets to the exception page with:

 'Trying to remove task context 17dc6ec8-ae37-4bca-9ed6-9cd4f13c6ad0, but it's in state RUNNING.'

**Comment by sixtam** [comment]
The same for the new TaskContextState.FAILED

**Comment by donarus** [comment]
Issue is invalid.
The true issue is to remove the benchmark "remove" button if the benchmark is not removable (running context).
