### ISSUE TITLE
Benchmark API - resubmitting failed benchmark too often 

### ISSUE THREAD

**Issue by sixtam** [ever-been/everBeen#162]
When a benchmark task fails over and over its getting resubmitted over and over. 

Also in WI I cannot kill the dammed thing because it's in ABORTED state and there is remove button when lucky these is the kill button .. but the task is long gone). And it throws exceptions when clicked with stack trace long as the Chinese wall

**Comment by kubamracek** [comment]
Fixed by d6c6dc6b8f3b5495c99c3b51781f624e68391106 and a5deab9a7b36bb6a8d30c17dee7ecf07d9922b7f. Added a hard limit (configurable) and a button into the benchmark detail page to disallow resubmits.
