### ISSUE TITLE
Detectors on FreeBSD

### ISSUE THREAD

**Issue by sixtam** [ever-been/everBeen#173]
On a FreeBSD machine I get 82.3 MB of free memory. In reality 8161M is free ... JavaDecector.java looks OK but somewhere the value gets reinterpreted?

**Comment by sixtam** [comment]
Also network interfaces are not detected ...

**Comment by kubamracek** [comment]
Fixed in https://github.com/ever-been/everBeen/commit/fa42eef9bf86c8e71bc162d893ad6a1a1e641162 and https://github.com/ever-been/everBeen/commit/e68087e9e3a456b01563bb383998e070e907658e
