### ISSUE TITLE
Cannot build BpkPlugin on ArchLinux

### ISSUE THREAD

**Issue by sixtam** [ever-been/everBeen#174]
mvn install -P buildBpkPlugin on ArchLinux fails with "Failed to read schema document 'xjc.xsd', because 'file' access is not allowed due to restriction set by the accessExternalSchema property."

Apparently the xjc.xsd file cannot be read from an external file. The only relevant page I found is http://openjdk.java.net/jeps/185 ... which is about Java 8 ?

Setting -Djavax.xml.accessExternalSchema=file does not seem to have any effect ... but this might be that maven is not propagating system properties, don't really know hot to set properties in maven. 

On other systems (FreeBsd, Fedora, Ubuntu) it just works. But the java version on ArchLinux is newer ("1.7.0_40", IcedTea 2.4.1) ...

**Comment by sixtam** [comment]
It works with the Oracle JDK. This might be either a bug in ArchLinux OpenJDK or in newer versions of OpenJDK. We will see ...

**Comment by radek-macha** [comment]
Hallelujah, there goes another mystery :)
