### ISSUE TITLE
code duplicity - cz.cuni.mff.been.common.Version#toString()

### ISSUE THREAD

**Issue by donarus** [ever-been/everBeen#18]
see method cz.cuni.mff.been.common.Version#toString() in module service_interfaces and see method ArrayUtils.toString(..) in same package of same module. ArrayUtils.toString should be used instead of standalone implementation. See (and/or remove) comment in code (cz.cuni.mff.been.common.Version#toString()).

**Comment by sixtam** [comment]
The correct function name in ArrayUtils is #join(..). Donarus, i think you can just go ahead and fix it, it's your discovery :).
