### ISSUE TITLE
Hazelcast logging and BeenAppender considered harmful

### ISSUE THREAD

**Issue by sixtam** [ever-been/everBeen#188]
It just does not work.

After fixing #182, another problem came up causing Hazelcast to exceedingly log. (Two nodes, one disconnects, the other logging "Could not connect to" over and over again.) That's because the BeenAppender logging the messages causes Hazelcast to emit the message again and so on.

**Comment by kubamracek** [comment]
lol

**Comment by sixtam** [comment]
After some discussion the workaround in 37a806a04a4fa53fbd06a88ddf4238b3f4d081d6 is the right thing to do.

This allows ability to debug Hazelcast while not getting in cyclic message logging. An user will want to debug Hazelcast because it cannot connect to the cluster anyway.
