### ISSUE TITLE
WI - exception and missing captions

### ISSUE THREAD

**Issue by sixtam** [ever-been/everBeen#192]
After the latest updates of the WI I get 

Render queue error in SetupRender[task/Tree:stateicon_2]: taskState nor taskContextState defined

org.apache.tapestry5.internal.services.RenderQueueException
Render queue error in SetupRender[task/Tree:stateicon_2]: taskState nor taskContextState defined

on task/tree.

Also on the overview page, Tasks overview, text is missing next to the task state icon.

I think its related ...

**Comment by sixtam** [comment]
FYI, the exception was thrown after I run task context (no benchmark)

**Comment by donarus** [comment]
My fault .. i will fix it later in the evening.
