### ISSUE TITLE
WI fails when generator taskof benchmark is removed and benchmark remains in HC

### ISSUE THREAD

**Issue by donarus** [ever-been/everBeen#193]
WI not working correctly on page http://localhost:8080/task/tree

When generator task of benchmark is removed and benchmark remains in HC memory, WI page throws exception. 

We should delete benchmark entry too when deleting generator entry of the benchmark from HC cluster.

**Comment by sixtam** [comment]
The task/tree page should survive such a ***\* up! And it did ... i had benchmark running overnight and the benchmark generator got evicted (that was before we got rid of it) ... no exception

And we should not allow to delete the generator from the WI task page - it should only be possible from the task/tree page, imo.
