### ISSUE TITLE
Doc - Persistence layer

### ISSUE THREAD

**Issue by sixtam** [ever-been/everBeen#196]
You know what to do ...
- role (what does it do)
- abstractness
  - storage for unknown user types
  - why does this layer need to be abstract and dumb
- AQL (description of the abstract querying language API)
- extension point (how is it meant to be extended, what is needed)
-  point out Hazelcast data distribution/scalability

**Comment by radek-macha** [comment]
Moved to https://github.com/ever-been/everDoc/issues/1
