### ISSUE TITLE
Refactor FileUtils cases

### ISSUE THREAD

**Issue by radek-macha** [ever-been/everBeen#34]
There are numerous calls on file creation, file name comparisons and other IO operations which are performed manually throughout the project. Analyze them and determine whether a custom FileUtils api is needed, or whether a standing implementation (e.g. apache.commons.io) will do.
Implement according changes (i.e. refactor standing code to use higher-level methods). If an implementation of custom FileUtils is required, proceed by TDD and place the implementation into the core module under package been.core.io.FileUtils.

**Comment by donarus** [comment]
Old code will be rewritten so this issue is no more relevant.
