### ISSUE TITLE
POM adaptation

### ISSUE THREAD

**Issue by radek-macha** [ever-been/everBeen#35]
Three global changes to POMs are required to bring the build pattern to the desired state:
- move all artifact version information into parent POM properties, with dependency declarations only using these properties, not explicit version
- remove all dependency declarations from the parent POM; distribute these among modules according to what each module needs
- manage module version from parent, which is done by removing explicit version declaration in modules; internal module-to-module dependency versions should be declared using the ${parent.version} placeholder

**Comment by radek-macha** [comment]
@donarus I'm thinking. Given that we'll want to configure logging in an overall configuration for the entire project, shouldn't we leave the slf4j and logback dependencies in the parent pom? Moreover, copying them into every module (everyone uses logging, or at least should...) seems like a mild violation of the DRY principle.

**Comment by donarus** [comment]
@radek-macha Hi. I understand your motives and totally agree with solution that you suggested. 

Just one more note about slf4j (and another often used libraries): some third party libraries could use slf4j too (but in different versions). It is possible that Maven figures it out without any user interaction but it is also possible that we will have to use Maven "exclusion" patterns to solve this issues.
