### ISSUE TITLE
Create a facade boot task loading

### ISSUE THREAD

**Issue by radek-macha** [ever-been/everBeen#38]
The current way of loading boot task is rather insidious and uses BPK files which have to be manually placed into a specific directory.
- Create a facade API for loading boot task BPKs
- Write unit tests against the API
- Implement the facade to use the JARs generated by Maven build (from target directories)
- Enrich the TaskDescriptor XSD with an optional, default false `isBootTask` attribute
- Set the `isBootTask` attribute to true when running services from the web interface and command-line interface
- In HostRuntime, during task creation, check the `isBootTask` attribute and, if a boot task is detected, use the boot task facade to load the BPK
- If possible, simplify the task creation mechanics in the process (remove superfluous TaskDescriptor duplication and intertwined method calls)

**Comment by donarus** [comment]
Closed as unwanted. Boot tasks will be implemented as services in new BEEN version.
