### ISSUE TITLE
UnmarshalException when opening the "run task" tab

### ISSUE THREAD

**Issue by radek-macha** [ever-been/everBeen#44]
With TM, HR and WI running on localhost, under Tasks->Run task, got:
RemoteException occurred in server thread; nested exception is: java.rmi.UnmarshalException: error unmarshalling arguments; nested exception is: java.lang.ClassNotFoundException: cz.cuni.mff.been.webinterface.modules.TasksModule$TasksQuery (no security manager: RMI class loader disabled)

Probably just another dependency needed.

**Comment by sixtam** [comment]
see #52
