### ISSUE TITLE
Review of #37 - JUnit and Mockito conventions wiki page

### ISSUE THREAD

**Issue by donarus** [ever-been/everBeen#45]
Hi,
 take a look on https://github.com/radek-macha/everBeen/wiki/JUnit-and-Mockito-conventions and try to find out if something important is missing. 

review of #37

**Comment by radek-macha** [comment]
@donarus I had a look and here's what I found:
- You're referencing documentations for JUnit and Mockito. For lazy people like me, a link couldn't hurt :)
- I'd kind of skip the section which talks about omitting static imports. I'm not sure, but I don't think the tests will work anywhere else but in the IDE if you just replace the imports with this feature. Which would be bad for auto-testing during maven builds.
- I took the liberty of correcting a typo in the best practices list previously.

**Comment by donarus** [comment]
already fixed
