### ISSUE TITLE
OneJar classloader does not play well with other jars.

### ISSUE THREAD

**Issue by sixtam** [ever-been/everBeen#51]
If I correctly understand how one-jar works, its classloader intercepts all attempts to load a class and will not load classes from the java classpath!

For example, detectortask cannot be run because DetectorClass is not found in the host_runtime.one-jar.jar.

**Comment by sixtam** [comment]
Workaround: instead of specifying java classpath on the command line when running a task, use _-Done-jar.class.path=other.jar|another.jar_

**Comment by sixtam** [comment]
I can get SR, HM, DA and CLI up and running using several hacks and workarounds (mostly focused on trying to convince one-jar to load needed classes). Move over CLI and HM seems to work and detectors run, SR and DA not tested.

Please if you about another way how to dead with this let me know. Donarus, how did you get services to run?

**Comment by donarus** [comment]
One-jar plugin will not be used in new BEEN implementation. If needed, maven assembly plugin will be used.
