### ISSUE TITLE
bpk-plugin and additional jars

### ISSUE THREAD

**Issue by sixtam** [ever-been/everBeen#56]
Currently there is no option to add an additional jar to the classpath in config.xml (besides the main jar in packageJarFile). 

Note that using one-jar does not work due to the one-jar classloader (which is installed with the host_runtime.one-jar.jar) and does not see all classes in another one-jar on the classpath.

See examples/task1 which almost runs fine  but cannot load hello.jar
(task-example-task needs two parameters src.file and dest.file + Tasks->Run Task)

**Comment by radek-macha** [comment]
The concept of loading dependencies has changed. Additional JARs should be loaded from the Software Repository in the future.
