### ISSUE TITLE
Basic SWRepository functionality

### ISSUE THREAD

**Issue by radek-macha** [ever-been/everBeen#68]
- SWRepo registers and unregisters itself to/from the cluster
- Responds to HTTP GET/PUT requests
- HTTP client uses local FS caching
- PUT is denied on duplicit entry (identifier equals)

**Comment by radek-macha** [comment]
Started work in b7eb72fb19bcac10d0e710be3c818eaf5729ec64

**Comment by radek-macha** [comment]
@donarus, @sixtam 
I keep coming across this all the time. I think it'd be better for the `Bpk` entity to become an interface with an `InputStream Bpk#getInputStream()` method, as opposed to `File Bpk#getFile()`. Would that be a problem?

**Comment by sixtam** [comment]
@radek-macha 
Not for me.

**Comment by radek-macha** [comment]
Some related refactoring in e1fae1b8e8c29098b4d77f705b0a84fd75e41b61.

**Comment by sixtam** [comment]
What is the expected behavior of concurrent uploads of the same BPK? The code suggests that concurrent uploaders will overwrite each others files.

**Comment by radek-macha** [comment]
See this issue's description for expected behavior.
As of now, the overwrite will happen. I am planning to revisit concurrency once the full features regarding Maven artifacts are implemented.

**Comment by radek-macha** [comment]
Artifact get/put (forgot to hash this): b6001b69ec00a71605d3dd0b5bd53f30c72671da

**Comment by radek-macha** [comment]
Collective decision lead to closing this issue without the duplicit entry denial for the moment, to allow easier debugging of other features. Covered by #74.

The SWRepository implements above features in a blocking way (i.e. one listener thread which blocks whenever it is processing a request). This is unsuitable for handling production payload. Covered by #75.
