### ISSUE TITLE
Implement log passing from Task to HR, implement log levels in Task

### ISSUE THREAD

**Issue by kubamracek** [ever-been/everBeen#72]

**Comment by sixtam** [comment]
Log passing done in ead80f830e708a3537cd9b72f36a17c542b4e54e.

What does "implement log levels in Task" mean?

And if I remember correctly creating Loggers should be handled better (currently only one instance of the logger exists)

**Comment by donarus** [comment]
I totally agree with @sixtam that each class (not an instance) should have its own logger (to be correct, each logger should have its own name (specified in constructor) and if 2 loggers are constructed in different classes with the same name, the identical logger should be used (or at least the logger behavior should be identical(behavior based on settings in logger configuration file)) - for example classes in package xx.yy.zz can have common logger with name "xxyzz" for example)...

And I think that @kubabrecka should implement getLogger(Class<?> klass) too.

If i understand it correctly, log levels in Task means that when someone configures his loggers (in some way ie. by changes of log levels in configuration file), then the logging behavior should correspond to this settings (ie. debug is disabled in configuration file = do not log debug messages etc.)

**Comment by sixtam** [comment]
Log level moved to #136. Closing.
