### ISSUE TITLE
support for "shell" tasks

### ISSUE THREAD

**Issue by donarus** [ever-been/everBeen#79]
Shell tasks must have possibility to communicate with running instance of the underlaying host runtime. 

In the HR (java based) and java-based tasks we are using 'jeromq' library (pure java implementation of 'zeromq' library).

As @kubabrecka mentioned, shell tasks could be supported by simple python script, which will be able to create json messages and send them using zeromq library.

If a user specify the task as a shell task, this python script will be included as a dependency and will be visible and usable from the script.

The goal of this issue is
- to implement this simple support python script
- to create sample runnable shell task

**Comment by sixtam** [comment]
Basic functionality implemented.
