### ISSUE TITLE
Add notification when changing state from SUSPENDED to RUNNING

### ISSUE THREAD

**Issue by kubamracek** [ever-been/everBeen#81]
Must be done from Task API, using the message pipe to Host Runtime.

**Comment by donarus** [comment]
Please, can you provide the more detailed description of this problem/feature?

**Comment by kubamracek** [comment]
When debugging, we want to track which processes are suspended (waiting for the debugger to attach) and which are already running. Because the started task is a separate process, the Host Runtime has no way of knowing, whether the new process is suspended or not. Inside the task process (in task api) we have to _somehow_ change the state of the task from suspended to running. This will be done using the message pipe between task and HR.

**Comment by donarus** [comment]
And how this 'dark magic' will be done in running task (in its Task API)? If we start JVM (process with java task) with 'suspend at startup' JVM option, we will have no possibility to call Task API, so it will be impossible to send notification to HR. So If I understand it correctly, we will have to use JDI (or something similar) and suspend process programatically after the 'I AM SUSPENDED' message has been sent. Am I missing something?

**Comment by sixtam** [comment]
It's the other way around. We need to inform HR that "I am running". It's for the case when we suspend a task and wait for a debbuger (or some other entity) to connect.

**Comment by sixtam** [comment]
Done in 1f8425eb6fd253bdcdeac5738253e7fb3e93d45d
