### ISSUE TITLE
Web Interface

### ISSUE THREAD

**Issue by donarus** [ever-been/everBeen#92]
Create base Tapestry based web interface skeleton with some sample components and pages which will help us to decide between Tapestry (or one of another frameworks) and JSP.

**Comment by kubamracek** [comment]
esthetrh

**Comment by kubamracek** [comment]
wwwefwef

**Comment by kubamracek** [comment]
ergeargaerg

**Comment by donarus** [comment]
closed due to irrelevance - basic web interface has been implemented long time ago and more specific issues are now opened.
