### ISSUE TITLE
RuntimeInfo is not removed when node is force-terminated

### ISSUE THREAD

**Issue by kubamracek** [ever-been/everBeen#99]
When incorrently terminating a node, it's RuntimeInfo entry in Hazelcast is not removed.

**Comment by sixtam** [comment]
This is known issue. Will get to it tomorrow.

By the way I incorrectly read the text of the issue as "RuntimeInfo is removed when gracefully terminating" (don't ask me why)... and went looking for it. Surprise, there really is such a bug ... the info can be re-inserted by the monitoring thread which is not terminated. So thanks for the report.
